# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: vionetaos-user-service
before:
  hooks:
  - go generate
  - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
  - go mod tidy
  - go test -race -v ./...
builds:
- id: vionetaos-user-service-amd64
  binary: build/sysroot/usr/bin/vionetaos-user-service
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  env:
  - CC=x86_64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - amd64
- id: vionetaos-user-service-arm64
  binary: build/sysroot/usr/bin/vionetaos-user-service
  # hooks:
  #   post:
  #     - upx --best --lzma -v --no-progress "{{ .Path }}"
  env:
  - CC=aarch64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm64
- id: vionetaos-user-service-arm-7
  binary: build/sysroot/usr/bin/vionetaos-user-service
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  env:
  - CC=arm-linux-gnueabihf-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
- id: vionetaos-user-service-migration-tool-amd64
  binary: build/sysroot/usr/bin/vionetaos-user-service-migration-tool
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=x86_64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - amd64
- id: vionetaos-user-service-migration-tool-arm64
  binary: build/sysroot/usr/bin/vionetaos-user-service-migration-tool
  # hooks:
  #   post:
  #     - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=aarch64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm64
- id: vionetaos-user-service-migration-tool-arm-7
  binary: build/sysroot/usr/bin/vionetaos-user-service-migration-tool
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=arm-linux-gnueabihf-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
archives:
- name_template: >-
    {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
  builds:
  - vionetaos-user-service-amd64
  - vionetaos-user-service-arm64
  - vionetaos-user-service-arm-7
  files:
  - build/**/*
- name_template: >-
    {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}
  id: vionetaos-user-service-migration-tool
  builds:
  - vionetaos-user-service-migration-tool-amd64
  - vionetaos-user-service-migration-tool-arm64
  - vionetaos-user-service-migration-tool-arm-7
  files:
  - build/sysroot/etc/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
release:
  github:
    owner: Vioneta
    name: VionetaOS-UserService
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
